### ISSUE TITLE
Can this be public?

### ISSUE THREAD

**Issue by tipiirai** [bketelsen/spotlight#2]
Hey Brian,

Nice website! I'm curious: can this repository be publicly available according to the Tailwind UI license? 

Thanks!

**Comment by mrinalcs** [comment]
I don't think so "usage **not allowed by the license**: Creating a repository of your favorite Tailwind UI components or templates (or derivatives based on Tailwind UI components or templates) and **publishing it publicly**."

@bketelsen @tipiirai 

[https://tailwindui.com/license](https://tailwindui.com/license)

**Comment by bketelsen** [comment]
from the FAQ of the template:

`Yep! As long as what you're building is some sort of actual website and not a derivative component library, theme builder, or other product where the primary purpose is clearly to repackage and redistribute our components, it's totally okay for that project to be open source.`

**Comment by tipiirai** [comment]
Cool. Thanks!

**Comment by hiteshjoshi** [comment]
This is literally the first point of whats not allowed in the license.

---
Examples of usage not allowed by the license:

    Creating a repository of your favorite Tailwind UI components or templates (or derivatives based on Tailwind UI components or templates) and publishing it publicly.
    
    
---

Literal meaning of `derivatives` : derive their value from an underlying asset, group of assets, or benchmark.

Ofcourse your public git repository derive value from an underlying asset of tailwind ui templates. And its not allowed.

And I have no idea where you derived this comment of yours : 

> Yep! As long as what you're building is some sort of actual website and not a derivative component library, theme builder, or other product where the primary purpose is clearly to repackage and redistribute our components, it's totally okay for that project to be open source.

`it's totally okay for that project to be open source` => NOPE. Because its `derivatives based on Tailwind UI components or templates`


https://github.com/bketelsen/spotlight/issues/3#issuecomment-1833205403
